export default {
    categories: [],
    categoryError: '',
    categoryErrorStatus: true,
    category: 'smartPhones',
    categorySearchVal: '',
    categoryList: [],
    products: [],
    product: '',
    productId: 1,
    singleProduct: {},
    popUpShow: false,
    popUpPreLoader: true,
    productPreLoader: false,
    tabloidShow: false,
    addAndQuantity: true,
    productQuantity: 1,
    totalProductPrice: '',
    totalProductPrice: [],
    totalPricesSum: 0,
    newArr: [],
    cartItems: [],
}